# ### Upload PDF
POST http://localhost:5000/api/pdf
Content-Type: application/json

{
  "title": "Integration Lecture",
  "url": "https://example.com/integration.pdf",
  "courseId": "67f441cfc746e468826da885"
}

### Get All PDFs
GET http://localhost:5000/api/pdf

### Get One PDF
GET http://localhost:5000/api/pdf/67f443e3da9d45b3ddeeefd3

### Update PDF
PUT http://localhost:5000/api/pdf/67f443e3da9d45b3ddeeefd3
Content-Type: application/json

{
  "title": "Updated PDF Title"
}

### Delete PDF
DELETE http://localhost:5000/api/pdf/67f443e3da9d45b3ddeeefd3
