# ### Create Summary
POST http://localhost:5000/api/resume
Content-Type: application/json

{
  "courseId": "67f441cfc746e468826da885",
  "content": "This is a summary of the integration chapter."
}

### Get All Summaries
GET http://localhost:5000/api/resume

### Get One Summary
GET http://localhost:5000/api/resume/67f44444da9d45b3ddeeefdd

### Update Summary
PUT http://localhost:5000/api/resume/67f44444da9d45b3ddeeefdd
Content-Type: application/json

{
  "content": "Updated summary content"
}

### Delete Summary
DELETE http://localhost:5000/api/resume/67f44444da9d45b3ddeeefdd
